#!/bin/bash

set -ouex pipefail

# Set default hostname
# ... this may not be needed depending on installer method, but it's a decent default
echo "cayo" > /etc/hostname
chmod 0644 /etc/hostname

# Repository setup
mkdir -p /etc/apt/keyrings
sed -i 's/main/main contrib non-free non-free-firmware/' /etc/apt/sources.list.d/debian.sources
tee /etc/apt/sources.list.d/debian-backports.sources > /dev/null <<EOF
Types: deb deb-src
URIs: http://deb.debian.org/debian
Suites: $(. /etc/os-release && echo "$VERSION_CODENAME")-backports
Components: main non-free-firmware
Enabled: yes
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
EOF

# Initial update
apt-get update -y

# Install Backports Kernel and Firmware
codename=$( . /etc/os-release && echo "$VERSION_CODENAME" )
echo "purging linux-image-*-$(dpkg --print-architecture)"
apt-get purge -y \
  "linux-image-*-$(dpkg --print-architecture)"
rm -rf /usr/lib/modules/*
apt list --installed |grep linux
echo "firmware-ipw2x00 firmware-ipw2x00/license/accepted boolean true" | debconf-set-selections
echo "firmware-ivtv firmware-ivtv/license/accepted boolean true" | debconf-set-selections
apt-get install -y -t "${codename}-backports" \
	dracut \
	linux-cpupower \
	"linux-image-$(dpkg --print-architecture)" \
	linux-perf \
	atmel-firmware \
	bluez-firmware \
	dahdi-firmware-nonfree \
	firmware-amd-graphics \
	firmware-ast \
	firmware-ath9k-htc \
	firmware-atheros \
	firmware-bnx2 \
	firmware-bnx2x \
	firmware-brcm80211 \
	firmware-carl9170 \
	firmware-cavium \
	firmware-cirrus \
	firmware-intel-graphics \
	firmware-intel-misc \
	firmware-intel-sound \
	firmware-ipw2x00 \
	firmware-ivtv \
	firmware-iwlwifi \
	firmware-libertas \
	firmware-linux-free \
	firmware-linux-nonfree \
	firmware-linux \
	firmware-marvell-prestera \
	firmware-mediatek \
	firmware-misc-nonfree \
	firmware-myricom \
	firmware-netronome \
	firmware-netxen \
	firmware-nvidia-graphics \
	firmware-qlogic \
	firmware-realtek \
	firmware-siano \
	firmware-sof-signed \
	firmware-zd1211

# Install Common Packages
apt-get install -y \
	bc \
	buildah \
	bzip2 \
	bzip2-doc \
	cpio \
	distrobox \
	docker-buildx \
	docker-compose \
	duperemove \
	file \
	firewalld \
	fwupd \
	hdparm \
	incus-agent \
	jq \
	less \
	locales \
	man-db \
	mergerfs \
	nano \
	nfs-common \
	nfs-kernel-server \
  pipewire \
	pciutils \
	pcp-zeroconf \
	picocom \
	podman \
	podman-docker \
	psmisc \
	openssh-client \
	openssh-server \
	qemu-guest-agent \
	rclone \
	samba \
	skopeo \
	smartmontools \
	smbclient \
	snapraid \
	socat \
	tar \
	tmux \
	tuned \
	tuned-ppd \
	unzip \
	usbip \
	usbutils \
	vim \
	wireguard-tools \
	xdg-dbus-proxy \
	xdg-user-dirs \
	zip \
	zstd

# TODO: add packages
# cockpit and friends
# dockhand quadlet?
# tailscale (external repo)
# incus and friends
# libvirt and friends
# zfs & sanoid/syncoid

# Get package list
mkdir -p /usr/share/cayo
apt list --installed > /usr/share/cayo/server-packages.txt

# disable services
systemctl disable nfs-server
systemctl disable nmbd
systemctl disable samba-ad-dc
systemctl disable smbd
systemctl disable winbind

# Update os-release info
sed -i 's/^PRETTY_NAME=.*/PRETTY_NAME="Cayo Linux"/' /usr/lib/os-release
sed -i 's/^NAME=.*/NAME="Cayo Linux"/' /usr/lib/os-release
sed -i 's/^ID=.*/ID="cayo"/' /usr/lib/os-release
echo "ID_LIKE=debian" >> /usr/lib/os-release

# Update build information in os-release
sed -i "s/^BUILD_ID=.*/BUILD_ID=\"$BUILD_ID\"/" /usr/lib/os-release
